### ISSUE TITLE
Motif view: sorting anitbody name

### ISSUE THREAD

**Issue by Raziel01** [TravisCG/summitwebsite#20]
In motif view, under "Plot options", the "Alphabetical by name" button doesn't work properly.

**Comment by TravisCG** [comment]
Looks like non of them worked. The bug is fixed.

**Comment by Raziel01** [comment]
The buttons still not working on Firefox. On chrome they are working.

**Comment by TravisCG** [comment]
I cannot reproduce the bug (I am using Firefox for developing the site). Have you tried to refresh your browser? If it is still not working, please add more detail: type of the motif, operating system, Firefox version.

**Comment by TravisCG** [comment]
Because there is no further info, I will close this.
